version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cocktailcove
    ports:
      - 127.0.0.1:5432:5432

